### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by egoist** [egoist/maid#1]
Find `typescript` module in current working directory and use it to compile `ts` or `typescript` code blocks.

**Comment by olstenlarck** [comment]
Whoah... How much :+1: ...

What is the use case? Tasks are pretty simple in most cases. What, you will define types in the task, why? Uh. Definitely don't seeing sense for typescript, but it would be just easy to add.

**Comment by egoist** [comment]
Yeah seems needless, I'll close it for now. Also I guess no editor has intellisense support for typescript in markdown code

**Comment by Marak** [comment]
It might be a good idea to consume or create a separate NPM module which can be responsible for spawning code snippets from multiple programming languages ( including languages like TypeScript, Lua, PHP, etc )

This way `maid` itself could focus itself on orchestrating tasks and this separate module would focus on spawning and executing tasks.

**Comment by olstenlarck** [comment]
the separate module for spawning is a good idea and it would handle the problems of #22 and #40
