### ISSUE TITLE
Run `N` scripts within task. 

### ISSUE THREAD

**Issue by AlvaroBernalG** [egoist/maid#20]
Hello good people of maid, 

Would it be possible if we could implement the ability to run synchronously `N` number of scripts within a Task?. 

E.j:
````markdown

## build 

Run task `test` after this

Retrieves the configuration from a website:

```bash
curl https://website.com/myConfiguration > config.json
```

Manipulate somehow the downloaded configuration: 

```js
const config = require('./config.json');
// ....
```

## test 

```bash
jest --config config.json 
```

````

**Comment by olstenlarck** [comment]
Strongly against that. Separate them in different tasks. Use some naming convention like `_` or etc.

**Comment by zephraph** [comment]
I think it sounds fairly useful. It'd be especially beneficial for the cases when you really needed to use different languages to solve a problem without polluting the task namespace. 

@olstenlarck Can you expound on your concerns?

**Comment by egoist** [comment]
How should we handle the task description if we add multiple scripts support in one task?

**Comment by zephraph** [comment]
I'd vote to just keep it as is. The top level text describes what the task does overall. Other paragraphs near code blocks can exist just to document those things, but I don't know that the help text really needs to document ever single thing that the task does.

**Comment by zephraph** [comment]
Taking the above example...

````
## build 

Responsible for building buildable things with configurable configurators. Also runs tests because those are important.

Run task `test` after this

Retrieves the configuration from a website:

```bash
curl https://website.com/myConfiguration > config.json
```

Manipulate somehow the downloaded configuration: 

```js
const config = require('./config.json');
// ....
```
````

**Comment by olstenlarck** [comment]
@zephraph because i think it's easier and separated.

But yea 

> without polluting the task namespace.

is good point.

**Comment by chrisdmacrae** [comment]
@zephraph @egoist on the additional comments, I agree with @zephraph

Verbose output could be added to maid that logs the descriptions, giving affordance there. 

This feature would make this a better task runner than Gulp.
