### ISSUE TITLE
Support /CONTRIBUTING\.md/i file?

### ISSUE THREAD

**Issue by tunnckoCore** [egoist/maid#25]
It is great place for describing a development flow and tasks.

**Comment by zephraph** [comment]
I think this is already covered via a [custom maid file](https://github.com/egoist/maid#use-a-custom-maidfile)

**Comment by olstenlarck** [comment]
Yes. But adding it to one of the defaults would be good too, because it is common places for such things and it definitely make sense.

**Comment by zephraph** [comment]
Open a PR. Here's where you'd need to do the change: https://github.com/egoist/maid/blob/d221b0b6e93e736c85cd6898a78a0ed710eb8723/lib/readMaidFile.js#L5-L9
