### ISSUE TITLE
change blockquotes to denote parallelism

### ISSUE THREAD

**Issue by ianstormtaylor** [egoist/maid#8]
Hey! Reading through the docs, I think there are two issues that are kind of inter-related...

1. That all "comments/description" seem to have to go in blockquotes?
2. That there's a special (hard to remember) syntax for "Run `x` after/before this (in parallel)".

I think there might be a simplification that will make writing the files easier, and make running things in parallel or not easier too.

First, I think all of the current use of blockquotes should be removed. Instead, let people write the commenting documentation just as normal paragraphs, since we already have the backticks as delineating code blocks to run. This makes the simple cases easier to remember. So the examples become:

```md
## lint

Run ESLint to ensure code quality

\```bash
eslint --fix
\```
```

After that, we now have blockquotes entirely freed up to be used for special syntax. I think they should be used to define parallelism. For things outside of block quotes, everything is run in series as it's encountered. So that instead of writing the "Run `x` before this", you can just add scripts in series:

```md
## lint

\```bash
eslint index.js
\```

## test

\```bash
maid lint
\```

\```bash
mocha test/index.js
\```
```

But then anything you put in a blockquote will be run in parallel, so you can easily do things like:

```md
## start

Run the watcher command and the web server.

> \```bash
> babel ./src --out-dir ./public --watch 
> \```
>
> \```bash
> serve ./public
> \```
```

This would run both the watcher and the web server in parallel, really easily.

You can even specify groups of parallel tasks separated by series tasks, by simply breaking the blockquotes into two with a series task in the middle.

**Comment by egoist** [comment]
The parallelism that blockquotes denote is for the tasks it's calling, i.e. : 

````markdown
## start

> Run `build:server` `build:client` before this in parallel.
````

This means calling tasks `build:server` `build:client` in parallel when you run `maid start`.

I guess blockquotes are indeed unnecessary here.

**Comment by egoist** [comment]
Now the block quotes are totally optional. All the paragraphs will be used as task description. 

Also <code>> Run &#x60;build:server&#x60; &#x60;build:client&#x60; before this in parallel.</code> now should be <code>Run tasks &#x60;build:server&#x60; &#x60;build:client&#x60; before this in parallel.</code>

**Comment by ianstormtaylor** [comment]
FWIW, the "Run x before this" is still super confusing. Since it's just a paragraph, it shows up in the readme as plain text to be read. Which to the user looks like a helpful recommendation, when really it's exactly the opposite of what you want them to do... since it's being handled automatically.
